import { StyleSheet } from "react-native";


export default StyleSheet.create({
    container:{
        backgroundColor:'#ffc4ff',
        height:'100%'
    },
    topContainer:{
        padding:15,
        backgroundColor:'#9575cd'
    },
    heyName:{
        fontSize:20,
        color:'black'
    },
    checkYour:{
        fontSize:25,
    },
    topContainerBottomRow:{
        flexDirection:'row',
        color:'black'
    },
    planTxt:{
        fontSize:25,
        fontWeight:'bold',
        color:'black',
        flex:1
    },
    btnAdd:{
        backgroundColor:'red',
        padding:15,
        borderRadius:10,
    },
    btnTxt:{
        fontSize:15,
        fontWeight:'bold',
        color:'white'
    },
    modalBackGround:{
        flex:1,
        backgroundColor:'rgba(0,0,0,0.5)',
        justifyContent:'center',
        alignItems:'center'
    },
    modalContainer:{
        width:'80%',
        backgroundColor:'white',
        paddingHorizontal:20,
        paddingVertical:30,
        borderRadius:20,
        elevation:20
    },
    header:{
        width:'100%',
        height:40,
        alignItems:'flex-end',
        justifyContent:'center',
        marginBottom:25,
    },
    txtInput:{
        width:'70%',
        margin:5,
        borderWidth:1,
        borderRadius:10,
        borderColor:'brown',
    },
    btnItemKaydet:{
        padding:10,
        borderWidth:1,
        borderColor:'green',
        borderRadius:10,
        backgroundColor:'#a5d6a7'
    },
    btnKaydetTxt:{
        color:'black',
        fontSize:14,
        fontWeight:'bold'
    },
})