import { StyleSheet } from "react-native";

export default StyleSheet.create({
    container:{
        flex:1,
        backgroundColor:'#4caf50'
    },
    header:{flex:1},
    imgPlant:{
        height:250,
        width:250,
        alignSelf:'flex-end',
        bottom:'60%'
    },
    bottom:{
        height:'50%',
        backgroundColor:'white',
        borderTopLeftRadius:12,
        borderTopRightRadius:12,
    },
    txtInfo:{
        alignSelf:'center',
        bottom:'45%',
        fontSize:20,
        fontWeight:'bold',
        color:'#1b5e20'
    },
    txtSoz:{
        alignSelf:'center',
        bottom:'25%',
        marginHorizontal:7,
        fontSize:20,
        fontWeight:'bold',
        color:'#1b5e20'
    },
    txtAuthor:{
        alignSelf:'flex-end',
        bottom:'24%',
        marginHorizontal:7,
        fontSize:17,
        fontWeight:'bold',
        color:'#a0af22'
    },
    btnSula:{
        padding:12,
        alignSelf:'flex-end',
        paddingHorizontal:25,
        borderRadius:10,
        backgroundColor:'#1b5e20',
        margin:15
    },
    txtSula:{
        fontSize:19,
        color:'#62efff',
        fontWeight:'bold'
    },
    txtSulamaTime:{
        fontSize:19,
        color:'#c8e6c9',
        fontWeight:'bold',
        margin:12
    }
})