import { StyleSheet } from "react-native";

export default StyleSheet.create({
    container:{
        padding:10,
        backgroundColor:'#a1887f'
    },
    pageHeader:{
        padding:15,
        backgroundColor:'#00796b',
        borderRadius:12,
        borderWidth:1,
        borderColor:'black'
    },
    headerTxt:{
        fontSize:20,
        fontWeight:'bold',
        color:'white'
    },
    imgPlansHeader:{
        height:240,
        width:350,
        alignSelf:'center',
        borderRadius:15,
        borderWidth:1,
        borderColor:'black',
        margin:10
    },
    pageBody:{
        padding:5
    },
    cardPlan:{
        padding:10,
        marginVertical:5,
        backgroundColor:'#004d40',
        borderRadius:12,
        borderWidth:1,
        borderColor:'black'
    },
    cardDetail:{
        padding:15,
        backgroundColor:'#00363a',
        borderRadius:10,
        margin:3
    },
    cardTxtHeader:{
        color:'white',
        fontSize:20,
        fontWeight:'bold',
        justifyContent:'center'
    },
    cardTxt:{
        color:'#e0f7fa',
        fontSize:17,
    },
    txtHomeWork:{
        paddingLeft:75
    },
    btnTxt:{
        fontSize:15,
        color:'white',
        fontWeight:'bold'
    },
    btnHomeWork:{
        padding:8,
        marginBottom:3,
        paddingHorizontal:14,
        marginLeft:220,
        backgroundColor:'#00251a',
        borderRadius:12,
        borderWidth:1,
        borderColor:'white'
    }
})