import { StyleSheet } from "react-native";

export default StyleSheet.create({
    topContainer:{
        padding:20,
        backgroundColor:'#ce93d8',
        borderBottomEndRadius:50
    },
    bottomContainer:{
        backgroundColor:'#5c007a',
        height:'100%'
    },
    callName:{
        fontSize:15,
        color:'black'
    },
    txtCheck:{
        fontSize:25,
        color:'black'
    },
    topContainerBottom:{
        flexDirection:'row',
    },
    txtPlanAnimal:{
        flex:1,
        marginBottom:10,
        fontSize:25,
        fontWeight:'bold',
        color:'black'
    },
    addBtn:{
        padding:15,
        marginBottom:12,
        backgroundColor:'red',
        borderWidth:1,
        borderRadius:10,
        alignSelf:'flex-end'
    },
    addBtnTxt:{
        color:'white',
        fontWeight:'bold',
        fontSize:15
    },
    modalBackGround:{
        flex:1,
        backgroundColor:'rgba(0,0,0,0.5)',
        justifyContent:'center',
        alignItems:'center'
    },
    modalContainer:{
        width:'80%',
        backgroundColor:'white',
        paddingHorizontal:20,
        paddingVertical:30,
        borderRadius:20,
        elevation:20
    },
    header:{
        width:'100%',
        height:40,
        alignItems:'flex-end',
        justifyContent:'center',marginBottom:25,
    },
    txtInput:{
        width:'70%',
        margin:5,
        borderWidth:1,
        borderRadius:10,
        borderColor:'brown',
    },
    btnItemKaydet:{
        padding:10,
        borderWidth:1,
        borderColor:'green',
        borderRadius:10,
        backgroundColor:'#a5d6a7'
    },
    btnKaydetTxt:{
        color:'black',
        fontSize:14,
        fontWeight:'bold'
    }

})