import { StyleSheet } from "react-native";

export default StyleSheet.create({
    container:{
        padding:15,
        width:'47.5%',
        backgroundColor:'#9c64a6',
        margin:5,
        borderRadius:15
    },
    headerCard:{
        flexDirection:'row',
    },
    closeIcon:{
        flex:1,
        alignSelf:'flex-start'
    },
    btnDuzenle:{
        alignSelf:'flex-end',
        backgroundColor:'#ffc4ff',
        padding:10,
        borderRadius:10
    },
    btnDuzenleTxt:{
        color:'#38006b',
        fontSize:15,
        fontWeight:'bold'
    },
    bookHeader:{
        flexDirection:'row',
        marginTop:3
    },
    bookName:{
        fontSize:18,
        color:'black',
        width:'87%'
    },
    bookAuthor:{
        fontSize:18,
        color:'black'
    },
    bookImage:{
        width:60,
        height:60
    },
    bottomInfo:{
        marginTop:3
    },
    bookPage:{
        fontSize:15,
    },
    unReadPage:{
        fontSize:15,
    },
    btnOkundu:{
        padding:10,
        paddingHorizontal:25,
        backgroundColor:'#b2fab4',
        alignSelf:'center',
        marginTop:5,
        borderRadius:10
    },
    btnOkunduTxt:{
        fontWeight:'bold',
        color:'#005005'
    },

})